#
# Makefile for the s3c framebuffer driver
#

obj-$(CONFIG_FB_S3C64XX)		+= s3cfb.o
obj-$(CONFIG_FB_S3C64XX)		+= s3cfb_spi.o
obj-$(CONFIG_FB_S3C64XX)		+= s3cfb_fimd4x.o
obj-$(CONFIG_FB_S3C64XX_S6D04D1)	+= s3cfb_s6d04d1.o
obj-$(CONFIG_FB_S3C64XX_S6D05A)		+= s3cfb_s6d05a.o
